=== kavispires/tardedivertida/src/utils/game-info.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "gameCode": { "type": "string" },
    "gameName": { "type": "string" },
    "version": { "type": "string" },
    "release": {
      "type": "string",
      "enum": ["dev", "beta", "stable", "planned", "cancelled", "deprecated", "paused"]
    },
    "releaseDate": {
      "type": "string",
      "pattern": "^(\\d{4}-\\d{2}-\\d{2}|0000-00-00)$"
    },
    "available": { "type": "boolean" },
    "title": {
      "type": "object",
      "properties": {
        "pt": { "type": "string" },
        "en": { "type": "string" }
      },
      "required": ["pt", "en"]
    },
    "popularName": {
      "type": "object",
      "properties": {
        "pt": { "type": "string" },
        "en": { "type": "string" }
      },
      "required": ["pt", "en"]
    },
    "inspiredBy": { "type": "string" },
    "summary": {
      "type": "object",
      "properties": {
        "pt": { "type": "string" },
        "en": { "type": "string" }
      },
      "required": ["pt", "en"]
    },
    "appearance": {
      "type": "object",
      "properties": {
        "primaryColor": { "type": "string" },
        "surfaceColor": { "type": "string" },
        "colorScheme": {
          "type": "string",
          "enum": ["light", "dark"]
        },
        "clouds": { "type": "string" },
        "cloudsAnimationType": {
          "type": "string",
          "enum": ["flow", "rising", "falling"]
        },
        "videoBackground": { "type": "boolean" }
      },
      "required": ["primaryColor", "clouds", "cloudsAnimationType", "colorScheme", "videoBackground"]
    },
    "rules": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "array",
          "items": { "type": "string" }
        },
        "en": {
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "required": ["pt", "en"]
    },
    "playerCount": {
      "type": "object",
      "properties": {
        "best": { "type": "integer" },
        "recommended": {
          "type": "array",
          "items": { "type": "integer" }
        },
        "min": { "type": "integer" },
        "max": { "type": "integer" }
      },
      "required": ["recommended", "min", "max", "best"]
    },
    "duration": {
      "type": "object",
      "properties": {
        "base": { "type": "number" },
        "perPlayer": { "type": "number" }
      },
      "required": ["base", "perPlayer"]
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "competitive",
          "cooperative",
          "same-time",
          "turn-based",
          "drawing",
          "writing",
          "guessing",
          "voting",
          "pairing",
          "push-your-luck",
          "brain-burner",
          "discussion",
          "puzzle",
          "timed",
          "images",
          "betting",
          "traitor",
          "achievements",
          "bots",
          "mobile-friendly"
        ]
      }
    },
    "options": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "key": { "type": "string" },
          "label": { "type": "string" },
          "description": { "type": "string" },
          "disabled": { "type": "boolean" },
          "kind": {
            "type": "string",
            "enum": ["switch", "checkbox", "radio"]
          },
          "values": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "label": { "type": "string" },
                "value": {
                  "type": ["string", "boolean"]
                }
              },
              "required": ["label", "value"]
            },
            "minItems": 1
          }
        },
        "required": ["key", "label", "kind", "description"]
      }
    }
  },
  "required": [
    "gameCode",
    "gameName",
    "version",
    "release",
    "releaseDate",
    "available",
    "title",
    "popularName",
    "inspiredBy",
    "summary",
    "rules",
    "playerCount",
    "tags",
    "appearance",
    "duration"
  ]
}

=== kavispires/tardedivertida/src/games/duetos/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "D",
  "gameName": "duetos",
  "version": "1.1.87",
  "release": "stable",
  "releaseDate": "2023-11-05",
  "available": true,
  "title": {
    "pt": "Duetos",
    "en": "Duets"
  },
  "popularName": {
    "pt": "Dos pares",
    "en": "To pair things"
  },
  "inspiredBy": "souD",
  "summary": {
    "pt": "Faça pares com as cartas como os outros jogadores",
    "en": "Pair the cards like the other players"
  },
  "appearance": {
    "clouds": "socks-clouds",
    "cloudsAnimationType": "falling",
    "primaryColor": "#5891e0",
    "colorScheme": "light",
    "videoBackground": true
  },
  "rules": {
    "en": [
      "Let's pair stuff?",
      "Each round a collection of things will be shown to you and you have to make pairs!",
      "You get points equal to how many players made the same pair as you",
      "After 5 rounds, the player with the most points wins"
    ],
    "pt": [
      "Vamos parear as coisas?",
      "A cada rodada uma coleção de coisas será mostrada e você tem que fazer pares!",
      "Você ganha pontos iguais a quantos jogadores fizeram o mesmo par que você",
      "Depois de 5 rodadas, o jogador com mais pontos vence"
    ]
  },
  "duration": {
    "base": 20,
    "perPlayer": 1
  },
  "playerCount": {
    "best": 4,
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 10
  },
  "tags": ["competitive", "pairing", "same-time", "achievements"],
  "options": [
    {
      "key": "nsfw",
      "kind": "switch",
      "label": "NSFW",
      "description": "Allow NSFW content",
      "values": [
        {
          "label": "Off",
          "value": false
        },
        {
          "label": "On",
          "value": true
        }
      ]
    },
    {
      "key": "withBots",
      "kind": "switch",
      "label": "Add Bots",
      "description": "Add bots to the game (for 2-3 player games only)",
      "disabled": true,
      "values": [
        {
          "label": "Off",
          "value": false
        },
        {
          "label": "On",
          "value": true
        }
      ]
    },
    {
      "key": "specialRounds",
      "kind": "checkbox",
      "label": "Special Rounds",
      "description": "Enable special rounds (Up to 3 special rounds will be used)",
      "values": [
        {
          "label": "Image Cards",
          "value": "images"
        },
        {
          "label": "Word",
          "value": "words"
        },
        {
          "label": "Celebrities",
          "value": "contenders"
        },
        {
          "label": "People/Suspects",
          "value": "suspects"
        },
        {
          "label": "Sprites (Emojis, Glyphs)",
          "value": "sprites"
        },
        {
          "label": "Avatars (Clubbers, Costumes, Super Heroes)",
          "value": "avatars"
        }
      ]
    }
  ]
}

=== kavispires/tardedivertida/src/games/barrados-na-alfandega/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "B",
  "gameName": "barrados-na-alfandega",
  "version": "0.0.5",
  "release": "planned",
  "releaseDate": "0000-00-00",
  "available": false,
  "title": {
    "pt": "Barrados Na Alfândega",
    "en": "Stuck On Customs"
  },
  "popularName": {
    "pt": "",
    "en": ""
  },
  "inspiredBy": "?????",
  "appearance": {
    "clouds": "cloud",
    "cloudsAnimationType": "flow",
    "primaryColor": "",
    "colorScheme": "light",
    "videoBackground": true
  },
  "summary": {
    "pt": "???",
    "en": "???"
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [3, 4, 5],
    "min": 3,
    "max": 6,
    "best": 0
  },
  "duration": {
    "base": 0,
    "perPlayer": 0
  },
  "tags": ["competitive"]
}

=== kavispires/tardedivertida/src/games/idade-da-preda/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "I",
  "gameName": "idade-da-preda",
  "version": "0.9.24",
  "release": "beta",
  "releaseDate": "2025-06-08",
  "available": false,
  "title": {
    "pt": "Idade da Preda",
    "en": "Tongue Age"
  },
  "popularName": {
    "pt": "O de criar a linguagem",
    "en": "The one about creating language"
  },
  "inspiredBy": "aDaDaD",
  "summary": {
    "pt": "Homens das cavernas tem que criar uma nova língua. Vamos nomear objetos?",
    "en": "Cavemen must create a new language. Let's name objects?"
  },
  "appearance": {
    "clouds": "cave-painting-cloud",
    "cloudsAnimationType": "flow",
    "primaryColor": "#c1b629",
    "colorScheme": "dark",
    "videoBackground": true
  },
  "rules": {
    "pt": [
      "Somos homens (e mulheres) das cavernas que precisam criar uma nova língua",
      "No início de cada rodada, os jogadores criam conceitos a partir de coisas disponíveis na tela, por exemplo: 'bola' + 'elefante' + 'melancia' dão a ideia de redondo. Para cada conceito será atribuído uma sílaba/som",
      "Depois, os jogadores devem criar um nome para um de seus três objetos secretos usando pelo menos duas sílabas/sons/conceitos disponíveis",
      "E finalmente, é hora de adivinhar o que os jogadores nomearam fazendo pares entre coisas e nomes. Você ganha 2 pontos por cada acerto, e 1 ponto pra cada jogador que acertar o seu",
      "O jogo dura 5 rodadas, indo da época da pedra, ao mundo medieval, tempos modernos e até um futuro próximo."
    ],
    "en": [
      "We are cavemen who need to create a new language",
      "At the beginning of each round, players create concepts from things available on the screen, for example: 'ball' + 'elephant' + 'watermelon' gives the idea of round. Each concept will be assigned a syllable/sound",
      "Then, players must name one of their three objects using the available syllables/sounds/concepts, using at least two syllables",
      "Finally, it's time to guess what players named. You earn 2 points for each correct guess, and 1 point for each player who guesses yours",
      "The game lasts 5 rounds, going from the Stone Age to the medieval world, modern times, and even a near future."
    ]
  },
  "playerCount": {
    "recommended": [4, 5, 6],
    "best": 5,
    "min": 2,
    "max": 10
  },
  "duration": {
    "base": 0,
    "perPlayer": 0
  },
  "tags": ["cooperative", "competitive", "writing", "guessing"],
  "options": [
    {
      "key": "nsfw",
      "kind": "switch",
      "label": "NSFW",
      "description": "Allow NSFW content",
      "values": [
        {
          "label": "Off",
          "value": false
        },
        {
          "label": "On",
          "value": true
        }
      ]
    }
  ]
}

=== kavispires/tardedivertida/src/games/pique-pega/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "P",
  "gameName": "pique-pega",
  "version": "0.0.2",
  "release": "planned",
  "releaseDate": "0000-00-00",
  "available": false,
  "title": {
    "pt": "Pique-Pega",
    "en": "The Chase"
  },
  "popularName": {
    "pt": "",
    "en": ""
  },
  "inspiredBy": "sroolF emosraeF",
  "summary": {
    "pt": "Corra do pegador e tente escapar!",
    "en": "Run from the chaser and try to escape!"
  },
  "appearance": {
    "clouds": "cloud",
    "cloudsAnimationType": "flow",
    "primaryColor": "",
    "colorScheme": "light",
    "videoBackground": true
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 10,
    "best": 5
  },
  "duration": {
    "base": 0,
    "perPlayer": 0
  },
  "tags": ["competitive"]
}
